### PR TITLE
Fix restore issue, add snapshot deletion after backup to s3

### PR DESCRIPTION
**Pull request by maorfr**

### CODE REVIEW

**Review by DeviaVir — APPROVED** [review]
:+1:

**Comment by DeviaVir** [comment]
You may want to take a look at `test_backup` and add `@patch('cassandras3.util.nodetool.sh')` there too, I think that's what the tests are currently breaking on.

You can also fully mock the clearsnapshot call.

**Comment by maorfr** [comment]
Last thing that was missing was an exception test for the clearsnapshot :)

**Comment by maorfr** [comment]
Good job on this project, saved me a ton of time!

**Review by DeviaVir — APPROVED** [review]

**Comment by DeviaVir** [comment]
available via pip as 0.1.3:
https://pypi.org/project/cassandras3/0.1.3/

**Pull request merged**
